### ISSUE TITLE
`eth_getBlockTransactionCountByHash` crashed if the block does not exist

### ISSUE THREAD

**Issue by calvinaco** [tharsis/ethermint#253]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. Start a chain
2. Call `eth_getBlockTransactionCountByHash` with a random block hash, e.g. 0xa6bb7b84c6276442394e025dafa6a8a89030c06daaedbeec570077983b1657ea
3. JSON RPC error returns
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

__Expected behavior:__ Return `null`

__Actual behavior:__ Return `"method handler crashed"`

__Additional info:__ [Include gist of relevant config, logs, etc.]

Server log

```
DEBU[0006] eth_getBlockTransactionCountByHash hash 0xa6bb7b84c6276442394e025dafa6a8a89030c06daaedbeec570077983b1657ea  fn=GetBlockTransactionCountByHash module=json-rpc src="namespaces/eth/api.go:271"
t=2021-07-10T19:05:45+0800 lvl=eror msg="RPC method eth_getBlockTransactionCountByHash crashed: runtime error: invalid memory address or nil pointer dereference\ngoroutine 289 [running]:\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc001732e40, 0x22, 0xc000fedd50)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/service.go:200 +0xba\npanic(0x5c3c540, 0x73eee90)\n\truntime/panic.go:969 +0x175\ngithub.com/tharsis/ethermint/ethereum/rpc/namespaces/eth.(*PublicAPI).GetBlockTransactionCountByHash(0xc0005da000, 0x426427c6847bbba6, 0xa8a8a6af5d024e39, 0xecbeedaa6dc03090, 0xea57163b98770057, 0x0)\n\tgithub.com/tharsis/ethermint/ethereum/rpc/namespaces/eth/api.go:278 +0x1b6\nreflect.Value.call(0xc0005becc0, 0xc000010620, 0x13, 0x5ef8bb2, 0x4, 0xc00054f1d0, 0x2, 0x3, 0xc00054f1e8, 0xc0017215a0, ...)\n\treflect/value.go:475 +0x8c7\nreflect.Value.Call(0xc0005becc0, 0xc000010620, 0x13, 0xc00054f1d0, 0x2, 0x3, 0x16, 0x0, 0x0)\n\treflect/value.go:336 +0xb9\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call(0xc0005bed20, 0x6534360, 0xc00153f6c0, 0xc001732e40, 0x22, 0xc0017215a0, 0x1, 0x1, 0x0, 0x0, ...)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/service.go:206 +0x2c5\ngithub.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc000566e10, 0x6534360, 0xc00153f6c0, 0xc0001739d0, 0xc0005bed20, 0xc0017215a0, 0x1, 0x1, 0x1)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:389 +0x8a\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc000566e10, 0xc001dce2d0, 0xc0001739d0, 0xc0005e06c0)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:337 +0x294\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc000566e10, 0xc001dce2d0, 0xc0001739d0, 0x650bd01)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:298 +0x1be\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc001dce2d0)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:139 +0x46\ngithub.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc000566e10, 0xc001721560)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:226 +0xd2\ncreated by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:222 +0x66\n"
```

**Comment by calvinaco** [comment]
I will work on this task
