### ISSUE TITLE
`eth_getBlockByHash` crashed if the block does not exist

### ISSUE THREAD

**Issue by calvinaco** [tharsis/ethermint#255]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. Start a chain
2. Call `eth_getBlockByHash` with a random block hash, e.g. 0xa6bb7b84c6276442394e025dafa6a8a89030c06daaedbeec570077983b1657ea
3. JSON RPC error returns
```
{
    "jsonrpc": "2.0",
    "id": 1,
    "error": {
        "code": -32000,
        "message": "method handler crashed"
    }
}
```

__Expected behavior:__ Return `null`

__Actual behavior:__ Return `"method handler crashed"`

__Additional info:__ [Include gist of relevant config, logs, etc.]

Server log

```
DEBU[0471] eth_getBlockByHash hash 0xad1328d13f833b8af722117afdc406a762033321df8e48c00cd372d462f48169 full true  fn=GetBlockByHash module=json-rpc src="namespaces/eth/api.go:702"
t=2021-07-10T20:34:38+0800 lvl=eror msg="RPC method eth_getBlockByHash crashed: runtime error: invalid memory address or nil pointer dereference\ngoroutine 5907 [running]:\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call.func1(0xc003a965c0, 0x12, 0xc0005a3d50)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/service.go:200 +0xba\npanic(0x5c3c520, 0x73eee90)\n\truntime/panic.go:969 +0x175\ngithub.com/tharsis/ethermint/ethereum/rpc/backend.(*EVMBackend).EthBlockFromTendermint(0xc000fecc40, 0x0, 0x0, 0x0, 0x6560000, 0xc00139fa80, 0xc001f3fa50, 0xb, 0x653f900, 0xc00051db70, ...)\n\tgithub.com/tharsis/ethermint/ethereum/rpc/backend/backend.go:150 +0x3a\ngithub.com/tharsis/ethermint/ethereum/rpc/backend.(*EVMBackend).GetBlockByHash(0xc000fecc40, 0x8a3b833fd12813ad, 0xa706c4fd7a1122f7, 0xc0488edf21330362, 0x6981f462d472d30c, 0x1, 0xc003a44dc0, 0x50, 0xc0049b0950)\n\tgithub.com/tharsis/ethermint/ethereum/rpc/backend/backend.go:135 +0x2a7\ngithub.com/tharsis/ethermint/ethereum/rpc/namespaces/eth.(*PublicAPI).GetBlockByHash(0xc000f7b4a0, 0x8a3b833fd12813ad, 0xa706c4fd7a1122f7, 0xc0488edf21330362, 0x6981f462d472d30c, 0x1, 0x0, 0x0, 0x0)\n\tgithub.com/tharsis/ethermint/ethereum/rpc/namespaces/eth/api.go:703 +0x194\nreflect.Value.call(0xc000060b80, 0xc0000325e0, 0x13, 0x5ef8b92, 0x4, 0xc003a17740, 0x3, 0x4, 0xc003a17758, 0xc003a98930, ...)\n\treflect/value.go:475 +0x8c7\nreflect.Value.Call(0xc000060b80, 0xc0000325e0, 0x13, 0xc003a17740, 0x3, 0x4, 0x16, 0x10, 0x0)\n\treflect/value.go:336 +0xb9\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call(0xc0010a7260, 0x6534340, 0xc003a6ea40, 0xc003a965c0, 0x12, 0xc003a98930, 0x2, 0x2, 0x0, 0x0, ...)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/service.go:206 +0x2c5\ngithub.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc003a46f30, 0x6534340, 0xc003a6ea40, 0xc003a42af0, 0xc0010a7260, 0xc003a98930, 0x2, 0x2, 0x2)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:389 +0x8a\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc003a46f30, 0xc003a988d0, 0xc003a42af0, 0xc0034276c0)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:337 +0x294\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc003a46f30, 0xc003a988d0, 0xc003a42af0, 0x650bd01)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:298 +0x1be\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc003a988d0)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:139 +0x46\ngithub.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1(0xc003a46f30, 0xc004685300)\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:226 +0xd2\ncreated by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc\n\tgithub.com/ethereum/go-ethereum@v1.10.3/rpc/handler.go:222 +0x66\n"

```

**Comment by calvinaco** [comment]
I am taking this task
