### ISSUE TITLE
Hardhat : fails to deploy contract

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#53]
__System info:__

MacOs

__Steps to reproduce:__

I am trying simple contract deploiement using hardhat, connecting the ethermint network (localhost:8545)

It gives me the following results >

```
➜  etherminttest git:(master) ✗ npx hardhat run --network ethermint scripts/deploy.js
ProviderError: invalid from address: address 'eth10jmp6sgh4cc6zt3e8gw05wavvejgr5pw2unfju' is not a valid ethereum hex address: invalid address
    at HttpProvider.request (/Users/thomasnguy/Documents/solidity/etherminttest/node_modules/hardhat/src/internal/core/providers/http.ts:46:19)
    at HDWalletProvider.request (/Users/thomasnguy/Documents/solidity/etherminttest/node_modules/hardhat/src/internal/core/providers/accounts.ts:142:34)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at EthersProviderWrapper.send (/Users/thomasnguy/Documents/solidity/etherminttest/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)


```

I will update the ticket after further investigation. Let me know if it is a known issue (I can also work on a fix)

__Expected behavior:__ [What you expected to happen]

Contract succesfully deployed

__Actual behavior:__ [What actually happened]

Error (see logs)

__Additional info:__ [Include gist of relevant config, logs, etc.]

Some stacktrace from the node

```
DEBU[0013] eth_chainId                                   fn=ChainId module=json-rpc src="ethereum/rpc/eth_api.go:107"
DEBU[0013] eth_chainId                                   fn=ChainId module=json-rpc src="ethereum/rpc/eth_api.go:107"
DEBU[0013] eth_chainId                                   fn=ChainId module=json-rpc src="ethereum/rpc/eth_api.go:107"
DEBU[0013] eth_estimateGas                               fn=EstimateGas module=json-rpc src="ethereum/rpc/eth_api.go:608"
I[2021-05-27|20:38:24.553] ABCIQuery                                    module=rpc path=/cosmos.auth.v1beta1.Query/Account data=0A2A65746831306A6D7036736768346363367A743365386777303577617676656A677235707732756E666A75 result="value:\"\\n\\323\\001\\n$/ethermint.types.v1alpha1.EthAccount\\022\\252\\001\\n\\205\\001\\n*eth10jmp6sgh4cc6zt3e8gw05wavvejgr5pw2unfju\\022U\\n./ethermint.crypto.v1alpha1.ethsecp256k1.PubKey\\022#\\n!\\003\\222\\356\\300\\374\\350\\301\\245\\243Y\\335\\362\\325\\307\\244fs\\213\\303\\3748\\267\\004m\\201\\270\\024\\323\\230\\021\\325\\257\\335 \\001\\022 \\305\\322F\\001\\206\\367#<\\222~}\\262\\334\\307\\003\\300\\345\\000\\266S\\312\\202';{\\372\\330\\004]\\205\\244p\" height:2 "
```

**Comment by fedekunze** [comment]
the issue is that we were setting the bech32 address instead of the hex one
