### ISSUE TITLE
Fail to deploy contract using truffle

### ISSUE THREAD

**Issue by thomas-nguy** [tharsis/ethermint#59]
__System info:__ 
MacOs

__Steps to reproduce:__

I am trying to run the solidity test manually by deploying the contract using 
```
truffle deploy --network ethermint
```

however it returns me the following error

```
Error: Returned error: method handler crashed
    at Object.ErrorResponse (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/lib/errors.js:28:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-core-requestmanager/lib/index.js:303:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/packages/provider/wrapper.js:107:1
    at XMLHttpRequest.request.onreadystatechange (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/web3/node_modules/web3-providers-http/lib/index.js:98:1)
    at XMLHttpRequestEventTarget.dispatchEvent (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request-event-target.js:34:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._setReadyState (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:208:1)
    at XMLHttpRequest.exports.modules.996763.XMLHttpRequest._onHttpResponseEnd (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:318:1)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/xhr2-cookies/dist/xml-http-request.js:289:47)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

__Expected behavior:__

Contract succesfully deployed

__Actual behavior:__ 

Errors see above

__Additional info:__ 

Some logs from the node 

```
DEBU[0468] eth_accounts                                  fn=Accounts module=json-rpc src="ethereum/rpc/eth_api.go:172"
DEBU[0468] eth_accounts                                  fn=Accounts module=json-rpc src="ethereum/rpc/eth_api.go:172"
DEBU[0468] eth_getBlockByNumber number -1 full false     fn=GetBlockByNumber module=json-rpc src="ethereum/rpc/eth_api.go:657"
I[2021-05-31|18:34:19.405] ABCIQuery                                    module=rpc path=/ethermint.evm.v1alpha1.Query/TxReceiptsByBlockHeight data= result="height:90 "
I[2021-05-31|18:34:19.405] ABCIQuery                                    module=rpc path=/ethermint.evm.v1alpha1.Query/BlockBloom data= result="code:22 log:\"rpc error: code = NotFound desc = block bloom not found: key not found\" height:90 codespace:\"sdk\" "
DEBU[0468] failed to query BlockBloom at height 90       error="rpc error: code = NotFound desc = rpc error: code = NotFound desc = block bloom not found: key not found" fn=EthBlockFromTendermint module=evm-backend src="ethereum/rpc/backend.go:176"
```

**Comment by thomas-nguy** [comment]
Additionnal information.

It seems the rpc endpoint getBlockByNumber is not working

```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", false],"id":1}' -H "Content-Type: application/json" http://localhost:8545

```

returns 

```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"method handler crashed"}}
```

**Comment by thomas-nguy** [comment]
closing the issue because it is the same as for #79
