### ISSUE TITLE
RPC method eth_feeHistory crashed: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by loredanacirstea** [tharsis/ethermint#974]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

ethermint v0.10.2

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

```
7:21AM ERR RPC method eth_feeHistory crashed: runtime error: invalid memory address or nil pointer dereference
```

__Additional info:__ [Include gist of relevant config, logs, etc.]

```
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #033[90m7:05AM#033[0m #033[1m#033[31mERR#033[0m#033[0m RPC method eth_feeHistory crashed: runtime error: invalid memory address or nil pointer dereference
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: goroutine 608042 [running]:
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*callback).call.func1()
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/service.go:200 +0x89
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: panic({0x1c29800, 0x347ce50})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/runtime/panic.go:1038 +0x215
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: math/big.(*Int).Cmp(0xc13c0c11a0, 0x4224b4)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/math/big/int.go:328 +0x22
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/tharsis/ethermint/rpc/ethereum/backend.sortGasAndReward.Less(...)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/tharsis/ethermint@v0.10.2/rpc/ethereum/backend/feebackend.go:29
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: sort.quickSort({0x245be60, 0xc13e1f79f8}, 0x18, 0x1bbf660, 0xc13e42fb01)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/sort/sort.go:218 +0x149
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: sort.Sort({0x245be60, 0xc13e1f79f8})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/sort/sort.go:231 +0x53
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/tharsis/ethermint/rpc/ethereum/backend.(*EVMBackend).processBlock(0xc112da3800, 0xc13e298140, 0xc13c0c13d8, {0xc1a544c640, 0x3, 0x0}, 0xc13e3b3c00, 0xc13c0c1440)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/tharsis/ethermint@v0.10.2/rpc/ethereum/backend/feebackend.go:94 +0x5bf
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/tharsis/ethermint/rpc/ethereum/backend.(*EVMBackend).FeeHistory(0xc112da3800, 0x1ea12a6, 0xc1a61307e0, {0xc1a544c640, 0x3, 0x4})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/tharsis/ethermint@v0.10.2/rpc/ethereum/backend/feebackend.go:182 +0x38f
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/tharsis/ethermint/rpc/ethereum/namespaces/eth.(*PublicAPI).FeeHistory(0xc000e9cd20, 0x0, 0xc102dcd800, {0xc1a544c640, 0x3, 0x4})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/tharsis/ethermint@v0.10.2/rpc/ethereum/namespaces/eth/api.go:231 +0x94
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: reflect.Value.call({0xc0193b9800, 0xc01b35f390, 0x7f2ca91d23c8}, {0x1e92efb, 0x4}, {0xc13bfc1780, 0x4, 0xc13bfcf900})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/reflect/value.go:543 +0x814
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: reflect.Value.Call({0xc0193b9800, 0xc01b35f390, 0x53d228}, {0xc13bfc1780, 0x4, 0x5})
ar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/usr/local/go/src/reflect/value.go:339 +0xc5
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*callback).call(0xc040f8c960, {0x24804f0, 0xc13c05e940}, {0xc13c074150, 0xe}, {0xc13be35360, 0x3, 0x4fb237})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/service.go:206 +0x405
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc1a544c620, {0x24804f0, 0xc13c05e940}, 0xc13c01a460, 0xc0017ed5e0, {0xc13be35360, 0x0, 0x203056})
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:389 +0x45
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc1308d7290, 0xc15a37d650, 0xc13c01a460)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:337 +0x239
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc1308d7290, 0xc261a5c800, 0xc13c01a460)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:298 +0xd1
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*handler).handleMsg.func1(0xc15a37d650)
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:139 +0x35
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:226 +0xc8
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: created by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc
Mar  6 07:05:26 evmos-clust-ar-mainnet evmosd[1211]: #011/go/pkg/mod/github.com/ethereum/go-ethereum@v1.10.16/rpc/handler.go:222 +0x92
```

**Comment by itsdevbear** [comment]
feeHistory big broken rn and causing a ton of problems, I have a local branch I can share, but it is not really that well tested nor prod ready.

**Comment by itsdevbear** [comment]
(my fix is hella ghetto too)
